### ISSUE TITLE
Authentication fails when KVNO is not 1

### ISSUE THREAD

**Issue by kristian-lesko** [wintoncode/vault-plugin-auth-kerberos#10]
Hello,

I cannot seem to get the authentication to work when the key in my keytab has a KVNO higher than one. I've looked into the code of both the plugin and the underlying `gokrb5` library extensively, but haven't been able to decipher the exact way the KVNO is parsed and checked (I suspect it's done in https://github.com/jcmturner/gokrb5/blob/master/messages/APReq.go#L124 but I'm not sure).

I don't have a way to reset the KVNO to 1 because of the way that the `ipa-getkeytab` command in FreeIPA works (increasing the KVNO after each keytab retrieval). I've tried to work-around this temporarily by [skipping the KVNO check](https://github.com/jcmturner/gokrb5/blob/master/keytab/keytab.go#L60), but the authentication started failing on an `integrity verification failed` error.

Could you please help me find out whether this is an issue with the `gokrb5` library itself, or rather in the way the plugin handles the keytab and passes it to the library? Thanks a lot.

**Comment by ah-** [comment]
Hey,

we've seen something similar, and I think fixed it via manually ensuring in ktutil addent (if i remember correctly) that the KVNO in the keytab is correct and up to date. I'm pretty sure we've ran it with a KVNO > 1.

Do you know what your kvno should be? Does the kvno in the keytab match? Any interesting log output?

The plugin does nothing to the keytab, it just takes it and plugs it straight into gokrb5.

**Comment by sambott** [comment]
Hi @kristian-lesko,
Did you have success here in the end? I use this plugin with a KVNO != 1, and it works but you have to have the KVNO in the keytab correct w.r.t your KDC.
The `gokrb5` library is not too forgiving with KVNOs. Typically I have found Kerberos libraries to pick up the right encryption key even when the KVNO is incorrect in the keytab, but that's not the case here. As long as the KVNO in your keytab and the service ticket match it should look it up.
I tried to start a discussion around this at https://github.com/jcmturner/gokrb5/issues/85 last year but I didn't have time to follow up - sorry!

**Comment by sambott** [comment]
@kristian-lesko - just had a thought. But that behavior might be occurring from a missing or badly formatted Service Principal Name. If the KDC is picking another entity's encryption key the KVNO will likely be different so will miss your keytab entry. If the KVNO check is bypassed it will find the keytab entry but will fail to decrypt the service token.

**Comment by kristian-lesko** [comment]
Hi @ah- @sambott,

this started working for us in the end; we did some custom patches of the plugin on our side (related to the way LDAP search for groups is performed by the plugin, as we use a slightly different group structure), but I'm not sure if these patches or a manual editing of the keytab helped in the end (it was a long time ago).

Anyway, this issue does not persist anymore, so this issue can probably be closed.
