### ISSUE TITLE
I suggest supporting request headers

### ISSUE THREAD

**Issue by jefferai** [wintoncode/vault-plugin-auth-kerberos#13]
See https://godoc.org/github.com/hashicorp/vault/logical#Request in combination with https://www.vaultproject.io/api/system/mounts.html#passthrough_request_headers-1

**Comment by ah-** [comment]
Yes that'd be nice, and doesn't look too difficult. Bit short on time atm, but might have a look.

Do you know if there are any plans yet to support sending back a 401 with header WWW-Authenticate: Negotiate?
That'd make it possible to use stock spnego against vault.

Protocol looks like this:
```
           C: GET dir/index.html

           S: HTTP/1.1 401 Unauthorized
           S: WWW-Authenticate: Negotiate

           C: GET dir/index.html
           C: Authorization: Negotiate a87421000492aa874209af8bc028
```

**Comment by jefferai** [comment]
No current plans.

**Comment by jefferai** [comment]
We have some raw response capabilities -- see https://godoc.org/github.com/hashicorp/vault/logical#pkg-constants -- but currently not a way to set custom response headers. If you're interested in adding such a capability get in touch and we can think about how it might best be done (and what drawbacks there may be).
