### ISSUE TITLE
policies not being assigned to authenticated kerberos user

### ISSUE THREAD

**Issue by pault28** [wintoncode/vault-plugin-auth-kerberos#7]
Hi,

This may be related to the latest version of vault/vault-plugin-auth-kerberos as this was working pre upgrade to latest versions of vault and vault-plugin-auth-kerberos.

Issue - I am able to authenticate correctly to vault using the plugin and I do get a token back. However the user is not granted the policies defined in auth/kerberos/groups/ldap_group. I can confirm that reading this config with root taken yields the required policies. The user which definetely belongs to ldap_group gets only the "default" vault permission.

```
auth/kerberos/groups/ldap_group  policies='devops_admin, systems_admin, vault_list_secrets'
 
vault read auth/kerberos/groups/ldap_group 
Key         Value
---         -----
policies    [devops_admin systems_admin vault_list_secrets]
```

Authenticating with plain ldap as the same user does work.

Does anyone have a working setup using vault `Vault v0.10.1 ` and the latest vault-plugin-auth-kerberos plugin?

Thanks.

**Comment by ah-** [comment]
Could you try running with `vault server -config=vault.hcl -log-level=debug`? It should log a something during group lookup, especially about what groups it got from ldap and what it keeps after filtering.

**Comment by pault28** [comment]
I get the correct groups for the user.

Could it be related to below?

> LDAP auth method case sensitivity: We now treat usernames and groups configured locally for policy assignment in a case insensitive fashion by default. Existing configurations will continue to work as they do now; however, the next time a configuration is written case_sensitive_names will need to be explicitly set to true.

Vault ldap has case insensitivity. My groups comeback in different case to what is used in policy assignment. Will try using exact case for kerberos to see if that fixes it.

**Comment by ah-** [comment]
Ah. The plugin still uses the ldap logic from vault 0.9, it's not easy to share the code so it's a bit duplicated. Longer term plan is to remove all that and deal with group lookups via the Identity mechanism, but currently don't have time to implement that.

**Comment by pault28** [comment]
Cool. It's definitely case sensitivity between auth policy and ldap group name. Once I used the exact case of the ldap group in the policy it works. Do you think this will be fixed soon? I guess it can be documented as a known issue for now. 

Thanks for the quick response once again @ah-

**Comment by ah-** [comment]
Unless someone else helps out it'll probably not be fixed, I'd rather spend the time working towards supporting the Identity stuff.
